import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { uploadRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Vendorly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextSSRPlugin routerConfig={extractRouterConfig(uploadRouter)} />
        {children}
        <Toaster richColors />
        <Footer />
      </body>
    </html>
  );
}
